# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9  # frozen: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--unsafe]
    -   id: check-json
    -   id: check-xml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-executables-have-shebangs
    -   id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
    -   id: requirements-txt-fixer

- repo: https://github.com/psf/black
  rev: e87737140f32d3cd7c44ede75f02dcd58e55820e  # frozen: 23.9.1
  hooks:
  - id: black
    args: ["--line-length", "120"]

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: 762c66ea96843b54b936fc680162ea67f85ec2d7  # frozen: v1.5.4
  hooks:
  - id: remove-tabs
    exclude: (Makefile$|\.bat$|\.cmake$|\.eps$|\.fits$|\.opt$)

- repo: https://github.com/pycqa/isort
  rev: dbf82f2dd09ae41d9355bcd7ab69187a19e6bf2f  # frozen: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black"]
    name: isort (python)
